# Spring app settings
spring.application.name=order-service
server.port=8081

# Database settings
spring.datasource.url=jdbc:postgresql://localhost:15432/order
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=admin
spring.datasource.password=donttouchmydatabase
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Liquibase settings
spring.liquibase.change-log=classpath:db.migrations/changelog-master.xml
spring.liquibase.enabled=true

# External services
menu.service.base-url=http://menu-service:8080/api
auth.service.base-url=http://auth-service:8082/api/auth

management.endpoints.web.exposure.include=mappings,health



